### ISSUE TITLE
Movimiento

### ISSUE THREAD

**Issue by SolidSLR** [SolidSLR/Laser-Dodge#3]
- Crear script de movimiento de la nave.
- Establecer límites en el mapa para evitar que la nave se salga del mismo.

**Comment by SolidSLR** [comment]
- IMPORTANTE: Los límites del mapa deben estar en una layer específica, de este modo podemos controlar que las balas ignoren su colisión.

**Comment by ricfdzgon** [comment]
Pregunta, queremos que el movimiento sea con WASD o con las flechas de dirección? O también podría ser las dos pero llevará mas vigilar posibles fallos.

**Comment by SolidSLR** [comment]
Creo que no es mala idea dar las dos opciones a la hora de mocerse. En cuanto a los posibles fallos, debería ser fácil de controlar que sólo se mueva si se pulsa una de las teclas. Si quieres, podemos probar a dar las dos posibilidades de primeras y, en caso de que de muchos problemas controlar que tecla se está pulsando, lo limitamos después.

**Comment by ricfdzgon** [comment]
Perfecto👍

**Comment by SolidSLR** [comment]
Se ha implementado el movimiento de la nave correctamente
